server:
  port: 8001
mybatis:
  #config-location: mybatis.xml # mybatis配置文件所在路径
  type-aliases-package: com.domain #配置domain包别名，那么就可以在mapper的sql配置文件中不用写全类名
  mapper-locations: classpath:mapper/ProductMapper.xml # mapper映射文件
spring:
  application:
    name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/customer?serverTimezone=GMT%2B8 # 数据库名称
    username: root
    password: 123456
eureka:
   client:
     registerWithEureka: true # 服务注册开关
     fetchRegistry: true # 服务发现开关
     serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
           defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
   instance:
     instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
     preferIpAddress: true #访问路径可以显示IP地址